#!/bin/bash
#
# GNOME Shell Version for Listed Extensions: 3.36
#
# Blyr:
wget --https-only -O ./modules/shell-extensions/blyr@yozoon.dev.gmail.com.zip https://extensions.gnome.org/extension-data/blyryozoon.dev.gmail.com.v8.shell-extension.zip
#
# Night Theme Switcher:
wget --https-only -O ./modules/shell-extensions/nightthemeswitcher@romainvigier.fr.zip https://extensions.gnome.org/extension-data/nightthemeswitcherromainvigier.fr.v36.shell-extension.zip
#
mkdir ./modules/shell-extensions/extracted
#
  for z in ./modules/shell-extensions/*.zip
do
  unar -d "$z" -o ./modules/shell-extensions/extracted/;
done
#
sudo mv ./modules/shell-extensions/extracted/* /usr/share/gnome-shell/extensions/
#
