#!/bin/bash
#
# GThumb PPA:
add-apt-repository -y ppa:dhor/myway
#
# System Update:
apt update
apt full-upgrade -y
#
# CODECs and Support:
apt install -y ttf-mscorefonts-installer ffmpeg lame exfat-utils gvfs-fuse youtube-dl
#
# Backend:
apt install -y flatpak tlp unar wget gamemode gnome-shell-extension-{gsconnect,caffeine,bluetooth-quick-connect} gnome-software gnome-software-plugin-flatpak flatpak chrome-gnome-shell gnome-sushi
#
# Theming and Wallpaper:
apt install -y adwaita-icon-theme-full gnome-backgrounds
#
# Core GNOME Apps:
apt install -y nautilus gedit totem evince file-roller gnome-calendar gnome-clocks gnome-control-center gnome-software geary lollypop
#
# GNOME Utils:
apt install -y gnome-calculator gnome-screenshot gnome-disk-utility gnome-font-viewer gnome-characters gnome-logs deja-dup gthumb
#
# GNOME User Utils:
apt install -y gnome-usage gnome-chess gnome-terminal
#
# GNOME Dev Utils:
#apt install -y gnome-system-monitor gnome-todo gnome-builder gnome-boxes devhelp sysprof baobab seahorse tilix nautilus-extension-tilix nautilus-extension-seahorse
#
# GNOME Games:
#apt install -y gnome-chess gnome-2048 gnome-mahjongg gnome-mines
#
