#!/bin/bash
#
# GNOME Defaults:
apt remove -y gnome-maps gnome-weather gnome-dictionary gnome-contacts gucharmap gimp
#
# GNOME Accessories:
apt remove -y transmission-common thunderbird
#
# GNOME Multimedia:
apt remove -y cheese shotwell simple-scan
#
# GNOME Optionals:
#apt remove -y eog rhythmbox
#
# GNOME Developer Tools:
apt remove -y remmina gnome-system-monitor gnome-power-manager baobab seahorse
#
# GNOME Games:
apt remove -y gnome-mahjongg gnome-mines gnome-sudoku aisleriot
#
# Clean-Up:
apt remove -y mpv gnome-tweaks
apt autoremove -y
#
# Removes Snap Store:
snap remove snap-store
#
