#!/bin/bash
#
# GNOME Accessories:
apt remove -y gnome-maps gnome-weather gnome-dictionary gucharmap transmission-common thunderbird
#
# GNOME Multimedia:
apt remove -y eog cheese gimp shotwell rhythmbox
#
# GNOME Developer Tools:
apt remove -y remmina gnome-system-monitor baobab
#
# GNOME Games:
apt remove -y gnome-mahjongg gnome-mines aisleriot
#
# Daily Driver Extras:
apt remove -y gnome-contacts simple-scan
#
# Clean-Up:
apt remove -y mpv gnome-tweaks
apt autoremove -y
#
# Removes Snap Store:
snap remove snap-store
#
