#!/bin/bash
#
### Enables System Configuration Overrides:
cp ./modules/syst-settings/60_genos* /usr/share/glib-2.0/schemas/
#
glib-compile-schemas --strict /usr/share/glib-2.0/schemas/
#
### Enables TLP:
systemctl enable tlp
#
### Increases Point of Battery Warning
sed -i.bak -e 's/^PercentageLow.*/PercentageLow=15/' -e 's/^PercentageCritical.*/PercentageCritical=5/' -e 's/^PercentageAction.*/PercentageAction=3/' -e 's/^CriticalPowerAction.*/CriticalPowerAction=Hibernate/' /etc/UPower/UPower.conf
#
### Hardens Default Network Privacy Settings
cp ./modules/syst-settings/network-privacy-hardening.conf /etc/NetworkManager/conf.d/
#
### Makes Yaru Shell Theme Modifications
cat ./modules/syst-settings/Yaru-Redux.css >> /usr/share/themes/Yaru-dark/gnome-shell/gnome-shell.css
#
