#!/bin/bash
#
### Enables System Configuration Overrides:
cp ./modules/syst-settings/* /usr/share/glib-2.0/schemas/
#
glib-compile-schemas --strict /usr/share/glib-2.0/schemas/
# 
### Enables TLP:
systemctl enable tlp
#
### Increases Point of Battery Warning
sed -i.bak -e 's/^PercentageLow.*/PercentageLow=15/' -e 's/^PercentageCritical.*/PercentageCritical=5/' -e 's/^PercentageAction.*/PercentageAction=3/' -e 's/^CriticalPowerAction.*/CriticalPowerAction=Hibernate/' /etc/UPower/UPower.conf
#
